# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-16 06:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('car_id', models.CharField(max_length=50, null=True, verbose_name='CAR')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('passenger', models.CharField(max_length=100, null=True, verbose_name='PASSENGERS')),
                ('purpose', models.CharField(max_length=100, null=True, verbose_name='PURPOSE')),
                ('destination', models.CharField(max_length=50, null=True, verbose_name='DESTINATION')),
                ('owner', models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bookingcar',
                'verbose_name_plural': 'bookingcars',
                'ordering': ('-start_time',),
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=50, verbose_name='CAR_ID')),
                ('car_name', models.CharField(max_length=50, verbose_name='CAR_NAME')),
                ('event_color', models.CharField(max_length=50, verbose_name='CAR')),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
            },
        ),
    ]
